# Generated by Django 6.0.3 on 2026-04-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_description_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/logos/'),
        ),
    ]
